server:
  port: 2333
  address: 0.0.0.0
lavalink:
  server:
    password: "youshallnotpass"
    sources:
      youtube: true
      bandcamp: true
      soundcloud: true
      twitch: true
      vimeo: true
      http: true
      local: false
    bufferDurationMs: 400
    youtubePlaylistLoadLimit: 6 # Number of pages at 100 each
    playerUpdateInterval: 5 # How frequently to send player updates to clients, in seconds
    youtubeSearchEnabled: true
    soundcloudSearchEnabled: true
    gc-warnings: true
    ratelimit:
      ipBlocks: [] # list of ip blocks
      excludedIps: [] # ips which should be explicit excluded from usage by lavalink
      strategy: "RotateOnBan" # RotateOnBan | LoadBalance | NanoSwitch | RotatingNanoSwitch
      searchTriggersFail: true # Whether a search 429 should trigger marking the ip as failing
      retryLimit: -1 # -1 = use default lavaplayer value | 0 = infinity | >0 = retry will happen this numbers times

logging:
  file:
    max-history: 1
    max-size: 3MB
  path: ./logs/

  level:
    root: INFO
    lavalink: INFO

metrics:
  prometheus:
    enabled: false
    endpoint: /metrics

sentry:
  dsn: ""
  environment: ""

plugins:
  lavasrc:
    providers:
      # Enable/disable deezer provider
      dzisrc:
        enabled: true
      # Enable/disable spotify provider
      spsrc:
        enabled: true
      # Enable/disable apple music provider
      apsrc:
        enabled: true
      # Enable/disable YouTube provider
      ytsrc:
        enabled: true
      # Enable/disable TTS provider
      ttssrc:
        enabled: true