services:
  # PostgreSQL Database
  - type: pserv
    name: ginsilog-postgres
    plan: standard
    env: docker
    disk:
      name: postgres-data
      mountPath: /var/lib/postgresql/data
      sizeGB: 10
    envVars:
      - key: POSTGRES_USER
        value: ginsilog
      - key: POSTGRES_PASSWORD
        generateValue: true
      - key: POSTGRES_DB
        value: ginsilogbot

  # Discord Bot
  - type: web
    name: ginsilog-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: SPOTIFY_CLIENT_ID
        sync: false
      - key: SPOTIFY_CLIENT_SECRET
        sync: false
      - key: DATABASE_URL
        sync: false