services:
  # PostgreSQL Database
  - type: pserv
    name: ginsilog-postgres
    plan: standard
    env: docker
    disk:
      name: postgres-data
      mountPath: /var/lib/postgresql/data
      sizeGB: 10
    envVars:
      - key: POSTGRES_USER
        value: ginsilog
      - key: POSTGRES_PASSWORD
        generateValue: true
      - key: POSTGRES_DB
        value: ginsilogbot

  # Discord Bot
  - type: web
    name: ginsilog-bot
    env: docker
    plan: standard
    autoDeploy: true
    healthCheckPath: /
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: GROQ_API_KEY
        sync: false 
      - key: SPOTIFY_CLIENT_ID
        sync: false
      - key: SPOTIFY_CLIENT_SECRET
        sync: false
      - key: DATABASE_URL
        fromService:
          type: pserv
          name: ginsilog-postgres
          envVarKey: POSTGRES_URL_NON_POOLING